### ISSUE TITLE
No data received in Data Explorer

### ISSUE THREAD

**Issue by C4rmel** [mgmeyers/obsidian-zotero-integration#257]
When using the _Zotero Integration: Insert notes into current document_ command, the Zotero search bar appears and shows papers correctly. However, when selecting a paper that has notes, just nothing happens. No error or anything.

When doing the same with the Zotero Data Explorer, it only says _No data retreived_.

I followed the given instructions.

- Obsidian Version 1.3.7 (Installer 1.3.7)
- Zotero Integration Version 3.0.7 installed and enabled
- Zotero Version 6.0.26
- Better BibTex for Zotero Version 6.7.98 installed
- Chicago Manual of Style 17th edition (full note) selected
- _Copy Biography_ works

<img width="457" alt="Screenshot 2023-08-03 at 13 22 35" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2701496/05f595b3-9a18-49e8-9bda-7947e7876585">
<img width="543" alt="Screenshot 2023-08-03 at 13 23 09" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2701496/4187f011-4a52-48bd-8a64-68f088e08729">
<img width="712" alt="Screenshot 20
<img width="831" alt="Screenshot 2023-08-03 at 13 24 20" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2701496/5946b511-7951-4dce-8457-ad7375cf5bb3">
23-08-03 at 13 23 39" src="https://github.com/mgmeyers/obsid
<img width="796" alt="Screenshot 2023-08-03 at 13 25 15" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2701496/574285d3-efc9-47c0-8b3d-020f2184e42f">
ian-zotero-integration/assets/2701496/05cb4762-b985-4c3f-b0db-e38d2ae
<img width="797" alt="Screenshot 2023-08-03 at 13 25 38" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2701496/a702a3f6-1a2a-4fee-b5ba-3ed9f85403a6">
dab1d">

**Comment by Edithnuaa** [comment]
I encountered this problem also! I haven't found any solution for this.

**Comment by rodrigolourencofarinha** [comment]
I also encountered this problem. The issue comes from the recent update of BetterBibTex [v6.7.98](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.98). Downgrade to v6.7.96 resolved the issue.

**Comment by rodrigolourencofarinha** [comment]
> I am having the same issue. How do you downgrade to the earlier version of BetterBibTex? Is this something one does through the BetterBibTex preferences in Zotero? Thank you.

Uninstall BetterBibTex addon from Zotero. Then, download and install this version: https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.96  😉

**Comment by harrisluket** [comment]
thanks!

**Comment by JimGrange** [comment]
Downgrading to BetterBibTex v6.7.96 hasn't worked for me. I am experiencing still exactly the same issue as OP.

**Comment by C4rmel** [comment]
Downgrading BetterBibTex to Version 6.7.96 solved the issue for me.

Thank you @rodrigolourencofarinha

**Comment by C4rmel** [comment]
Re-opened because issue still not fully fixed:  

Zotero Data Explorer shows that annotations are present; however, still, no annotations are imported when using either _Import notes_ or _Inster notes into current document_.  No error or warning is created in the Developer Console.
Similar to #240

**Comment by mgmeyers** [comment]
@C4rmel "Import notes" and "Insert notes into current document" do not pull from the data in the Data Explorer, instead they grab notes like these from Zotero:

<img width="357" alt="Screenshot 2023-08-04 at 9 44 34 AM" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2694747/b2d13b4d-21c2-43fa-9cdd-5b8046f3ed20">

I'm able to import notes using v6.7.96 on my end. Double check the that item you're trying to import notes for contains a note. If it does, see if Obsidian's developer console displays any errors. You can open it with ctrl + shift + i / command + opt + i

**Comment by DannyHatcher-Git** [comment]
If I understand correctly, the v6.7.96 is what I need to 'downgrade' to.

I will explore how to do that but is this something that will be 'fixed' any time soon?

**Comment by mgmeyers** [comment]
@DannyHatcher-Git upgrading to the latest version (6.7.104) of better bibtex should fix this issue

**Comment by C4rmel** [comment]
@mgmeyers thank you for the help and your work. It is highly appreciated!

The issue persisted even after updating to the latest version (6.7.104) of better bibtex.

However, I have identified a potential cause for the issue. It seems when duplicates of the entry are present in other Zotero libraries, the annotations from the last imported entry are imported, independent from which was selected using the zotero selector (red zotero entry field which pops up when using the _Insert notes into current document_ command.

The Zotero entry that I was using still had the same issue I opened this issue for. However, when using a different entry with annotations, it worked. The paper entry which resulted in the issue was also present as a duplicate in two group libraries. In those group libraries, no annotations were connected. When selecting the entry with the _Insert notes into current document_ command in Obsidian, I made sure to select the entry in my main Library _My Library _, as shown in the screenshot above. But no notes were inserted. When I connected annotations to the last imported Zotero entry in one of the group libraries but still selected the entry from my main library, the annotations were imported to Obsidian.

Trying to summarize it:
**Attempt 1**
Main Library
- Paper Entry with connected annotations, imported 2021

1st Group Library
- Same Paper Entry with no connected annotations, imported 2022

2nd Group Library
- Same Paper Entry with no connected annotations, imported 2023

=>  Using _Insert notes into current document_ command, selecting the Main Library entry, no annotations are imported.


**Attempt 2**
Main Library
- Paper Entry with connected annotations, imported 2021

1st Group Library
- Same Paper Entry with no connected annotations, imported 2022

2nd Group Library
- Same Paper Entry **now with** connected annotations, imported 2023

=>  Using _Insert notes into current document_ command, **still** selecting the Main Library entry, annotations are imported.


**Attempt 3**
Main Library
- Paper Entry with **no** connected annotations, imported 2021

1st Group Library
- Same Paper Entry with no connected annotations, imported 2022

2nd Group Library
- Same Paper Entry **with** connected annotations, imported 2023

=>  Using _Insert notes into current document_ command, **still** selecting the Main Library entry, annotations are imported.


I can also confirm from the time stamp from the imported annotations that they are imported from the 2nd Group Library entry, even when selecting the Main Library entry in the Zotero selector when using the _Insert notes into current document_ command.

Hope this was understandable and helps.

**Comment by padasch** [comment]
Downgrading to https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.94 solved this issue for me

**Comment by arvdv** [comment]
Reopening because I am getting a similar issue!

Importing a document from a group library when an older copy exists in my main library seems to cause the behaviour described above - import happens, but without any annotations. I've downgraded my installation of BetterBibTex from 6.7.163 to 6.7.96, which half-fixed the issue. I can now import notes and annotations from the older copy in the main library again, but can still not import from the group library. This issue _only_ seems to occur for files that have an older 'sibling' in another library, and it seems to be happening in both directions (i.e. a reference copied from a group library into the main library will exhibit the same behaviour). Weirdly enough, doing a 'fresh' import in the group library does not resolve the issue.

I am running the latest version of the Zotero Integration (3.1.7), Obsidian v1.5.11, Zotero v6.0.37, and BetterBibTex v6.7.96.
