### ISSUE TITLE
Persist overwriting contents

### ISSUE THREAD

**Issue by corytaitchison** [mgmeyers/obsidian-zotero-integration#301]
Recently, persist has been consistently overwriting its contents on re-import. 

For example, I have a template:
```
{% persist "notes" %}
{% endpersist %}
```

On first import, I get a new document with
```
%% begin notes %%%% end notes %%

%% Import Date: 2023-10-21T17:01:27.582+01:00 %%
```

I then update this to
```
%% begin notes %%
Test
%% end notes %%

%% Import Date: 2023-10-21T17:01:27.582+01:00 %%
```

and rerun the import. The note is overwritten and becomes
```
%% begin notes %%%% end notes %%
```

If I then update the file to 
```
%% begin notes %%
Test
%% end notes %%
```

And re-run the import, this time it DOES persist, giving
```
%% begin notes %%
Test
%% end notes %%

%% Import Date: 2023-10-21T17:05:36.638+01:00 %%
```

But if I import again, the cycle repeats and the note is overwritten. This same cycle happens every time, regardless of which file I import. I have disabled all other community plugins, just Zotero Integration is activated. 

Any ideas why? It was working as expected last week.

**Comment by corytaitchison** [comment]
Just to add, it's not to do with the presence of `%% Import Date...`, if I get rid of that line, it still overwrites the contents.

**Comment by corytaitchison** [comment]
Update: the issue seems to be with Line 383 of `bbt/export.ts`. Commenting that out fixes the problem. This was changed in  commit aa2e834. 

Not too sure why this is the case...

**Comment by corytaitchison** [comment]
A temporary fix while retaining functionality is to replace Line 383 with

```
    reg = /%% begin (.+?) %%([\w\W]*?)%% end \1 %%/gi;
    hasPersist = reg.test(main);
```

For some reason, running the regular expression from `PersistExtension` causes the error, but writing it out explicitly is fine...

**Comment by mgmeyers** [comment]
Thanks for the investigation @corytaitchison. I'm pretty sure I found the culprit (see here: https://github.com/mgmeyers/obsidian-zotero-integration/commit/d76155b253d209c4131a20fef7c6706d91f46b1d#diff-5fddb95078270a303d25df3604946e8509937f4532fffac875a28eff32a0506eR187)

**Comment by mgmeyers** [comment]
Also, let me know if you still encounter issues with this

**Comment by Hamsquishery** [comment]
Many, many thanks for isolating & fixing the problem. I'm new in all _this_, and thought I had done something wrong!

**Comment by SimonB97** [comment]
Hi, i'm new to Obsidian AND Zotero, could you help me applying this fix? The persist functionality would be pretty neat, thanks!

**Comment by Hamsquishery** [comment]
@SimonB97, I think if you access the current versions of Obsidian-Zotero Integration community plugion for Obsidian, it should fix the problem.

**Comment by SimonB97** [comment]
Thanks for your response, although I think I got the newest versions of both already installed and it still won't work (see my previous answer)

**Comment by rajesh-s** [comment]
I still encounter this issue on v3.1.7 of the plugin. Is anyone else in the same boat?
